### ISSUE TITLE
Mockup for the Main Menu

### ISSUE THREAD

**Issue by Philipp-M** [co0k/TreasureHunt#10]
Acceptance 
==========
a well defined mockup for the Main Menu View, containing buttons for Settings, User profile, Map and Ranking views

**Comment by co0k** [comment]
![mainview](https://cloud.githubusercontent.com/assets/10153810/7229326/be6b5082-e762-11e4-8fe6-257fe0083ac7.png)

**Comment by co0k** [comment]
https://moqups.com/#!/edit/poorpot@gmail.com/7rM9wfJ8
