### ISSUE TITLE
Client-Server protocol technology

### ISSUE THREAD

**Issue by Philipp-M** [co0k/TreasureHunt#13]
Acceptance 
==========
A good API for the connection between the server and the client

**Comment by dAmihl** [comment]
Klingt für mich kurz gesagt so: 
WebSockets für ständigen Datenaustausch. 
REST für Daten auf Nachfrage. 
Bin i da richtig?

**Comment by Philipp-M** [comment]
Im ganz Groben schon, mir gefallen Websockets eher besser, erstens wird es als Nachfolger von Sachen wie REST und co angesehen(siehe z.B. hier: http://www.infoq.com/news/2012/02/websockets-rest), zweitens mag ich das bidirektionale Prinzip und natürlich als Perfektionist den Overhead beim Senden:
Bei HTTP/REST: socket aufmachen, HTTP Protokoll-Overhead, socket zumachen).
Bei Websockets: socket aufmachen, Daten über TCP austauschen(ist also kein HTTP-Header dabei)  und wenn man mit allem fertig ist den socket wieder zumachen.

Ein Beispiel mit Android kann man sich hier anschauen: http://www.elabs.se/blog/66-using-websockets-in-native-ios-and-android-apps 
Dort wird Java-Websocket(http://java-websocket.org/) verwendet, was man sowohl für den Server als auch für Android(Client) verwenden kann(zwei Fliegen mit einer Klappe ;) )

**Comment by dAmihl** [comment]
Die Implementation mit der Java-Websocket API scheint mir wirklich recht simpel zu sein und schaut in den Beispielen gut aus.
Mit z.B. JSON Parsern (Strings sendet das Ding ja schon mal ^^) für Server und Client sollt die Kommunikation damit echt recht schnell gemacht sein :)

Also ich bin dafür :+1:

**Comment by Philipp-M** [comment]
Wenn keiner dagegen ist(entnehme ich jetzt einfach mal der "Resonanz" der anderen ;), kann man den/die/das Issue mal schließen oder?
