### ISSUE TITLE
Server API

### ISSUE THREAD

**Issue by Philipp-M** [co0k/TreasureHunt#14]
Acceptance 
==========
A good API for the managment on the server

**Comment by dAmihl** [comment]
Play! Framework oder Nooq

**Comment by dAmihl** [comment]
Jersey, RestX

**Comment by Philipp-M** [comment]
Ich fasse bis jetzt mal zusammen: 
* Für die Datenbank:
    * Jooq 
        * SQL Derivat(MariaDB, MySQL, SQLite, etc)
* Für die Kommunikation:
    * Java-WebSocket

Das war es erstmal an (Haupt-)APIs, es werden sicher noch weitere kleine Bibliotheken wie z.B. ein [Quadtree](https://github.com/kirstywilliams/quadtree) zur effizienten Suche/Rückgabe von Truhen etc. gebraucht, aber als grobes Grundgerüst ständen dann die APIs erstmal.

**Comment by dAmihl** [comment]
Passt, sollen wir den PS Leitern das per Mail schicken?
Wie sehen die nächsten Pläne aus?

**Comment by BenjaminGAUGLER** [comment]
@Philipp-M hat das Ganze schon zusammen gefasst.
Einzig noch erwähnenswert ist hier, die Verwendung von Jetty embedded für das Serverfrontend.
Damit schließe ich den Issue.
