### ISSUE TITLE
Data structures for the Server(-program)

### ISSUE THREAD

**Issue by Philipp-M** [co0k/TreasureHunt#18]
Acceptance
=========

e.g. SQL-statements for the database itself and for example UML/Java classes for the server program
@Philipp-p 
@Philipp-M

**Comment by Philipp-M** [comment]
UML diagram added for the Treasure data model inside the server. Focus was on flexibility, so a lot of interfaces were used, and instead of enums strings were used, because of easy expandability in case of new treasure/content-types (examples included in the UML diagram(quest, badge etc.))

**Comment by Philipp-M** [comment]
UML diagram added for the User data model inside the server, similar as the Treasure model.
Mostly implemented the Java classes for both, the User data and the Treasure model.
As maybe noticed almost all the classes are readonly(with the exception of the constructor of course). My focus was on stability, so that only the creator should change anything on the object. Maybe it is a little bit to strictly, so it is possible to also make those classes partly writeable. But I suggest to avoid it if it is possible(thinking of threadsafety etc.)

**Comment by Philipp-p** [comment]
sql for treasure part of server DB already online

**Comment by Philipp-M** [comment]
TODO:
Treasure history has to be added to the treasure data structure, something like: "was opened by user id". If it ain't open, save a negative number for example...

**Comment by Philipp-p** [comment]
Treasure holds now a last_userid for that purpose

**Comment by Philipp-p** [comment]
Data structures are now more or less final
