### ISSUE TITLE
Client Server data exchange

### ISSUE THREAD

**Issue by dAmihl** [co0k/TreasureHunt#38]
It should be possible to use the ServerCommunicationDAO (and the class implementing it: ServerCommunication) to parse and send objects to the server, and receiving messages and parsing them into datastructures.

**Comment by ethragur** [comment]
See https://github.com/ethragur/SMRTMS/blob/master/app/src/main/java/client/smrtms/com/smrtms_client/controller/ServerControl.java takes JSON files and parses them back to the Object

**Comment by Philipp-M** [comment]
Well since JSON RPC is used  for the protocol and JSON for the data itself, I guess this is solved then
