### ISSUE TITLE
JSON Constructors and Readers for all data structures

### ISSUE THREAD

**Issue by Philipp-M** [co0k/TreasureHunt#46]
Acceptance:
=========
Json constructors and readers for all data structures(Treasure, User, HighscoreList, etc.) as said in the title

**Comment by ethragur** [comment]
This takes about 10min https://github.com/ethragur/SMRTMS/blob/master/app/src/main/java/client/smrtms/com/smrtms_client/controller/JSONReader.java

**Comment by BenjaminGAUGLER** [comment]
@Philipp-M  are this and #47 still necessary? Or can we close them?
