### ISSUE TITLE
Parsing ArrayLists into and from JSON

### ISSUE THREAD

**Issue by BenjaminGAUGLER** [co0k/TreasureHunt#56]
The Server must be able to parse ArrayLists containing Treasure objects into JSON. And the client must be able to decode these Json strings.

**Comment by Philipp-M** [comment]
I think this is solved since it is easy to parse to arrays and convert them into arraylists

**Comment by BenjaminGAUGLER** [comment]
Thanks for closing. I really forgot to do that.
As of how easy this whole thing - just look inside the RequestHandlerTest I wrote.
